### ISSUE TITLE
关于爬取外网资源

### ISSUE THREAD

**Issue by ddumbledoree** [Qiantigers/crawlTelegraph#1]
初学者一时兴起想爬telegraph的内容，但没有大佬的技术力。请问是怎样做到翻墙requests时“没有防火墙或代理服务器阻止连接”？运行.exe的时候很顺利，但看python源代码mian.py好像没看到相应的操作....a_a

**Comment by CalmXin** [comment]
> 初学者一时兴起想爬telegraph的内容，但没有大佬的技术力。请问是怎样做到翻墙requests时“没有防火墙或代理服务器阻止连接”？运行.exe的时候很顺利，但看python源代码mian.py好像没看到相应的操作....a_a

requests有个参数是porxies，如果你本地用的是clash

那么就可以加一个

```py
proxies = { 'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890' }
```
'

**Comment by ddumbledoree** [comment]
妙，解决了，感谢
